#!/usr/bin/env bash
# Preserve toolkit-owned /etc state across SteamOS atomic updates and recover
# tuning files from the previous image when upgrading an older installation.
set -euo pipefail

KEEP_DIR=/etc/atomic-update.conf.d
LEGACY_KEEP_FILE="$KEEP_DIR/bc250-steamos.conf"
PREVIOUS_ETC=/etc/previous
BACKUP_DIR=/var/lib/steamos-atomupd/etc_backup
COMPONENTS=(compute power cec aic)

COMPUTE_SETTINGS=(
    /etc/bc250-cu-live-manager.conf
)
POWER_SETTINGS=(
    /etc/cyan-skillfish-governor-smu/config.toml
    /etc/cyan-skillfish-governor-smu/freq-state
    /etc/bc250-smu-oc.conf
)

log() { echo "[bc250-update] $*"; }
die() { echo "[bc250-update] $*" >&2; exit 1; }
require_root() { [[ $EUID -eq 0 ]] || die "Run with sudo."; }

write_keep_file() {
    local component="$1" target="$KEEP_DIR/bc250-$1.conf" tmp
    tmp=$(mktemp "$KEEP_DIR/.bc250-$component.XXXXXX")
    {
        printf '%s\n' '# Toolkit state preserved by SteamOS atomic updates.' \
            '# Generated by bc250-update-persistence.sh.'
        case "$component" in
            compute)
                cat << 'EOF'
/etc/bc250-cu-live-manager.conf
/etc/systemd/system/bc250-cu-live-manager.service
/etc/systemd/system/multi-user.target.wants/bc250-cu-live-manager.service
EOF
                ;;
            power)
                cat << 'EOF'
/etc/bc250-acpi-heal.sh
/etc/bc250-smu-oc.conf
/etc/cyan-skillfish-governor-smu/**
/etc/dbus-1/system.d/com.cyan.SkillFishGovernor.conf
/etc/systemd/system/bc250-acpi-heal.service
/etc/systemd/system/bc250-cpufreq.service
/etc/systemd/system/bc250-gpu-freq-restore.service
/etc/systemd/system/bc250-smu-oc.service
/etc/systemd/system/cyan-skillfish-governor-smu.service
/etc/systemd/system/multi-user.target.wants/bc250-acpi-heal.service
/etc/systemd/system/multi-user.target.wants/bc250-cpufreq.service
/etc/systemd/system/multi-user.target.wants/bc250-gpu-freq-restore.service
/etc/systemd/system/multi-user.target.wants/bc250-smu-oc.service
/etc/systemd/system/multi-user.target.wants/cyan-skillfish-governor-smu.service
EOF
                ;;
            cec)
                cat << 'EOF'
/etc/bc250-cec-poweroff-standby.sh
/etc/systemd/system-sleep/bc250-cec-amp.sh
/etc/systemd/system/bc250-cec-poweroff-standby.service
/etc/systemd/system/multi-user.target.wants/bc250-cec-poweroff-standby.service
EOF
                ;;
            aic)
                cat << 'EOF'
/etc/aic8800-ensure-modules.sh
/etc/aic8800-paths.conf
/etc/modprobe.d/aic8800.conf
/etc/udev/rules.d/40-aic8800-modeswitch.rules
/etc/usb_modeswitch.d/1111:1111
/etc/systemd/system/aic8800-modules.service
/etc/systemd/system/multi-user.target.wants/aic8800-modules.service
EOF
                ;;
            *) rm -f "$tmp"; die "Unknown component: $component" ;;
        esac
    } > "$tmp"
    chmod 644 "$tmp"
    mv -f "$tmp" "$target"
    log "Atomic-update keep list installed at $target"
}

component_has_state() {
    case "$1" in
        compute) [[ -e /etc/bc250-cu-live-manager.conf || -e /etc/systemd/system/bc250-cu-live-manager.service ]] ;;
        power)   [[ -e /etc/cyan-skillfish-governor-smu || -e /etc/bc250-smu-oc.conf \
                    || -e /etc/systemd/system/bc250-acpi-heal.service ]] ;;
        cec)     [[ -e /etc/bc250-cec-poweroff-standby.sh || -e /etc/systemd/system-sleep/bc250-cec-amp.sh ]] ;;
        aic)     [[ -e /etc/aic8800-paths.conf || -e /etc/systemd/system/aic8800-modules.service ]] ;;
        *)       return 1 ;;
    esac
}

install_keep_list() {
    require_root
    local requested="${1:-all}" component
    mkdir -p "$KEEP_DIR"
    if [[ -f "$LEGACY_KEEP_FILE" ]]; then
        for component in "${COMPONENTS[@]}"; do
            component_has_state "$component" && write_keep_file "$component"
        done
        rm -f "$LEGACY_KEEP_FILE"
        log "Legacy wholesale keep list split into component drop-ins."
    fi
    case "$requested" in
        all)
            for component in "${COMPONENTS[@]}"; do
                write_keep_file "$component"
            done
            ;;
        compute|power|cec|aic) write_keep_file "$requested" ;;
        *) die "Unknown component: $requested" ;;
    esac
}

latest_archive() {
    local archive found=""
    for archive in "$BACKUP_DIR"/*.tar.xz; do
        [[ -f "$archive" ]] || continue
        found="$archive"
    done
    printf '%s\n' "$found"
}

recover_settings() {
    require_root
    local requested="${1:-all}" force=0 target rel source archive="" tmp restored=0 previous=0 component
    local -a settings=() recovery_components=()
    shift || true
    case "${1:-}" in
        "") ;;
        --force) force=1 ;;
        *) die "Unknown recovery option: $1" ;;
    esac
    case "$requested" in
        compute)
            settings=("${COMPUTE_SETTINGS[@]}")
            recovery_components=(compute)
            ;;
        power)
            settings=("${POWER_SETTINGS[@]}")
            recovery_components=(power)
            ;;
        all)
            settings=("${COMPUTE_SETTINGS[@]}" "${POWER_SETTINGS[@]}")
            recovery_components=(compute power)
            ;;
        *) die "Unknown recovery component: $requested" ;;
    esac
    tmp=$(mktemp -d /tmp/bc250-update-recovery.XXXXXX)
    archive=$(latest_archive)
    if [[ -z "$archive" && -f "$PREVIOUS_ETC/README" ]]; then
        previous=1
    fi

    for target in "${settings[@]}"; do
        if [[ -e "$target" && $force -eq 0 ]]; then
            continue
        fi
        rel=${target#/etc/}
        source="$PREVIOUS_ETC/$rel"
        if [[ $previous -eq 0 ]]; then
            [[ -n "$archive" ]] || continue
            tar -tJf "$archive" "etc/$rel" >/dev/null 2>&1 || continue
            rm -rf "$tmp/etc"
            tar -xJf "$archive" -C "$tmp" "etc/$rel"
            source="$tmp/etc/$rel"
        fi
        [[ -f "$source" && ! -L "$source" ]] || continue
        install -D -m 644 "$source" "$target"
        log "Recovered $target"
        restored=$((restored + 1))
    done

    for component in "${recovery_components[@]}"; do
        install_keep_list "$component"
    done
    if [[ $restored -eq 0 ]]; then
        log "Tuning files are already present or absent from the update backup."
    else
        log "Recovered $restored tuning file(s). Reinstall the selected components to regenerate services."
    fi
    rm -rf "$tmp"
}

show_status() {
    local component state
    for component in "${COMPONENTS[@]}"; do
        state=pending
        [[ -f "$KEEP_DIR/bc250-$component.conf" ]] && state=installed
        log "$component keep list: $state"
    done
    if [[ -f "$LEGACY_KEEP_FILE" ]]; then
        log "legacy wholesale keep list: installed"
    fi
    if [[ -d "$PREVIOUS_ETC" ]]; then
        log "Previous /etc edits: $PREVIOUS_ETC"
    fi
    if compgen -G "$BACKUP_DIR/*.tar.xz" >/dev/null; then
        log "Atomupd archives: $BACKUP_DIR"
    fi
}

SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
C0=$'\033[0m'; CB=$'\033[1m'; CD=$'\033[2m'; CI=$'\033[7m'
CG=$'\033[32m'; CY=$'\033[33m'; CR=$'\033[31m'; CC=$'\033[36m'
TUI_CURSOR_HIDDEN=0

tui_show_cursor() {
    if [[ $TUI_CURSOR_HIDDEN -eq 1 ]]; then
        printf '\033[?25h'
        TUI_CURSOR_HIDDEN=0
    fi
}
trap tui_show_cursor EXIT

menu_select() {
    local title="$1"; shift
    local items=("$@") n=$# cur=0 drawn=0 key rest i label badge hint
    local lines=$((n + 4))
    printf '\033[?25l'; TUI_CURSOR_HIDDEN=1
    while true; do
        if [[ $drawn -eq 1 ]]; then printf '\033[%dA' "$lines"; fi
        printf '\r\033[K%s\n' "${CB}${CC}${title}${C0}"
        printf '\033[K%s\n' "${CD}  up/down move - Enter select - q back${C0}"
        for i in "${!items[@]}"; do
            IFS='|' read -r label badge hint <<< "${items[$i]}"
            if [[ $i -eq $cur ]]; then
                printf '\033[K%s\n' "  ${CI}${CB} > ${label} ${C0} ${badge}"
            else
                printf '\033[K%s\n' "     ${label}  ${badge}"
            fi
        done
        IFS='|' read -r label badge hint <<< "${items[$cur]}"
        printf '\033[K\n\033[K%s\n' "  ${CD}${hint}${C0}"
        drawn=1
        IFS= read -rsn1 key || { tui_show_cursor; return 1; }
        if [[ $key == $'\033' ]]; then
            rest=""
            IFS= read -rsn2 -t 0.05 rest || true
            key+="$rest"
        fi
        case "$key" in
            $'\033[A'|k) if (( cur > 0 )); then cur=$((cur - 1)); else cur=$((n - 1)); fi ;;
            $'\033[B'|j) if (( cur < n - 1 )); then cur=$((cur + 1)); else cur=0; fi ;;
            "")          MENU_CHOICE=$cur; tui_show_cursor; return 0 ;;
            q|Q|$'\033') tui_show_cursor; return 1 ;;
        esac
    done
}

pause_key() {
    echo
    printf '%s' "${CD}-- press any key to return to the menu --${C0}"
    IFS= read -rsn1 || true
    printf '\r\033[K'
}

keep_badge() {
    if [[ -f "$KEEP_DIR/bc250-$1.conf" ]]; then
        printf '%s' "${CG}[protected]${C0}"
    else
        printf '%s' "${CY}[pending]${C0}"
    fi
}

run_menu_action() {
    local rc=0
    echo
    if [[ $EUID -eq 0 ]]; then
        bash "$SELF" "$@" || rc=$?
    else
        sudo bash "$SELF" "$@" || rc=$?
    fi
    if [[ $rc -ne 0 ]]; then
        echo -e "${CR}${CB}[bc250-update]${C0} action failed (exit $rc)"
    fi
    pause_key
}

show_menu_status() {
    echo
    show_status
    pause_key
}

cmd_menu() {
    [[ -t 0 && -t 1 ]] || die "The menu needs an interactive terminal. Use '$0 help' for CLI commands."
    while true; do
        local items=(
            "Protect compute|$(keep_badge compute)|Preserve compute-unit routing and its boot service."
            "Protect power|$(keep_badge power)|Preserve power services, GPU tuning, and CPU tuning."
            "Protect CEC|$(keep_badge cec)|Preserve CEC poweroff and sleep integration."
            "Protect AIC8800|$(keep_badge aic)|Preserve AIC8800 service and device configuration."
            "Protect all components||Install every component keep list."
            "Recover compute settings||Restore CU routing from the newest atomupd snapshot."
            "Recover power settings||Restore GPU and CPU tuning from the newest atomupd snapshot."
            "Recover all settings||Restore compute and power settings from the newest snapshot."
            "Show status||Show component protection and available recovery sources."
        )
        menu_select "SteamOS update persistence" "${items[@]}" || { echo; break; }
        case $MENU_CHOICE in
            0) run_menu_action install compute ;;
            1) run_menu_action install power ;;
            2) run_menu_action install cec ;;
            3) run_menu_action install aic ;;
            4) run_menu_action install all ;;
            5) run_menu_action recover compute ;;
            6) run_menu_action recover power ;;
            7) run_menu_action recover all ;;
            8) show_menu_status ;;
        esac
    done
}

cmd_help() {
    cat << EOF
Usage: $0 {install [compute|power|cec|aic|all] | recover [compute|power|all] [--force] | status | menu | help}

Run with no arguments in a terminal to open the interactive menu.
EOF
}

if [[ $# -eq 0 ]]; then
    cmd_menu
    exit 0
fi

case "$1" in
    install) shift; install_keep_list "${1:-all}" ;;
    recover) shift; recover_settings "${1:-all}" "${2:-}" ;;
    status)  show_status ;;
    menu)    cmd_menu ;;
    help|-h|--help) cmd_help ;;
    *) cmd_help >&2; exit 1 ;;
esac
