import os
import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AIC_INSTALLER = ROOT / "aic8800/steamdeck-setup.sh"
AIC_HELPER = ROOT / "aic8800/aic8800-ensure-modules.sh"
AIC_SERVICE = ROOT / "aic8800/aic8800-modules.service"
AUDIO_INSTALLER = ROOT / "bc250-audio-fix/patch-driver.sh"
AUDIO_ROLLBACK = ROOT / "bc250-audio-fix/rollback.sh"
AUDIO_BOOT_CONFIG = ROOT / "bc250-audio-fix/boot-config.sh"
AUDIO_CLEAN = ROOT / "bc250-audio-fix/clean.sh"
AUDIO_PREREQS = ROOT / "bc250-audio-fix/ensure-build-prereqs.sh"
METRICS_PATCH = ROOT / "bc250-audio-fix/bc250-cyan-skillfish-gpu-telemetry.patch"
GFXCLK_PATCH = ROOT / "bc250-audio-fix/bc250-cyan-skillfish-gfxclk.patch"
GFX1013_ATTESTATION_PATCH = (
    ROOT / "bc250-audio-fix/bc250-gfx1013-attestation.patch"
)


class DriverLifecycleTests(unittest.TestCase):
    def test_status_entrypoints_are_read_only_and_do_not_require_sudo(self):
        for script, prefix in (
            (AIC_INSTALLER, "[aic8800]"),
            (AUDIO_INSTALLER, "[bc250-amdgpu]"),
        ):
            result = subprocess.run(
                ["bash", str(script), "status"],
                capture_output=True,
                text=True,
            )
            self.assertIn(prefix, result.stdout)
            self.assertIn("state:", result.stdout)
            self.assertIn(result.returncode, (0, 1))

    def test_missing_amdgpu_scheduler_policy_prints_install_command(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            env = os.environ.copy()
            env.update(
                {
                    "SCHED_CONFIG": str(root / "bc250-amdgpu.cfg"),
                    "GRUB_DEFAULT": str(root / "grub"),
                    "GRUB_CFG": str(root / "grub.cfg"),
                    "PROC_CMDLINE": str(root / "cmdline"),
                    "AMDGPU_KEEP_FILE": str(root / "bc250-amdgpu.conf"),
                }
            )

            result = subprocess.run(
                ["bash", str(AUDIO_BOOT_CONFIG), "status"],
                capture_output=True,
                text=True,
                env=env,
            )

            self.assertEqual(result.returncode, 1)
            self.assertIn("scheduler policy: not configured", result.stdout)
            self.assertIn(
                f"install with: sudo bash {AUDIO_BOOT_CONFIG} install",
                result.stdout,
            )

    def test_active_scheduler_policy_handles_root_only_generated_grub(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            config = root / "bc250-amdgpu.cfg"
            keep = root / "bc250-amdgpu.conf"
            cmdline = root / "cmdline"
            policy = root / "sched_policy"
            protected = root / "efi"
            config.write_text(
                "# BC-250 AMDGPU scheduler policy managed by "
                "bc250-audio-fix/boot-config.sh.\n"
                "# Required by the GFX1013 async-compute queue repair.\n"
                'GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT:-} '
                'amdgpu.sched_policy=2"\n',
                encoding="utf-8",
            )
            keep.write_text(
                "# Toolkit state preserved by SteamOS atomic updates.\n"
                "# Generated by bc250-update-persistence.sh.\n"
                f"{config}\n"
                "/etc/systemd/system/bc250-persistence-recovery.service\n"
                "/etc/systemd/system/local-fs.target.wants/"
                "bc250-persistence-recovery.service\n"
                "/etc/systemd/system/var-lib-bc250\\x2dcontrol.mount\n"
                "/etc/systemd/system/local-fs.target.wants/"
                "var-lib-bc250\\x2dcontrol.mount\n",
                encoding="utf-8",
            )
            cmdline.write_text("quiet amdgpu.sched_policy=2\n", encoding="utf-8")
            policy.write_text("2\n", encoding="utf-8")
            protected.mkdir(mode=0o000)
            bindir = root / "bin"
            bindir.mkdir()
            stat = bindir / "stat"
            stat.write_text(
                '#!/bin/sh\n[ "$2" = %u ] && { echo 0; exit; }; echo 644\n',
                encoding="utf-8",
            )
            stat.chmod(0o755)
            env = os.environ.copy()
            env.update(
                {
                    "SCHED_CONFIG": str(config),
                    "GRUB_DEFAULT": str(root / "default-grub"),
                    "GRUB_CFG": str(protected / "grub.cfg"),
                    "PROC_CMDLINE": str(cmdline),
                    "SCHED_POLICY_PARAM": str(policy),
                    "AMDGPU_KEEP_FILE": str(keep),
                    "PATH": f"{bindir}:{env['PATH']}",
                }
            )
            try:
                result = subprocess.run(
                    ["bash", str(AUDIO_BOOT_CONFIG), "status"],
                    check=True,
                    capture_output=True,
                    text=True,
                    env=env,
                )
            finally:
                protected.chmod(0o700)

            self.assertIn("configured and active", result.stdout)

            policy.write_text("0\n", encoding="utf-8")
            pending = subprocess.run(
                ["bash", str(AUDIO_BOOT_CONFIG), "status"],
                check=True,
                capture_output=True,
                text=True,
                env=env,
            )
            self.assertIn("configured; reboot needed", pending.stdout)

    def test_audio_uninstall_routes_noninteractive_slot_rollbacks(self):
        with tempfile.TemporaryDirectory() as directory:
            bindir = Path(directory)
            call_log = bindir / "sudo-call"
            (bindir / "id").write_text(
                "#!/bin/sh\n[ \"$1\" = -u ] && { echo 1000; exit 0; }\n"
                "exec /usr/bin/id \"$@\"\n",
                encoding="utf-8",
            )
            (bindir / "sudo").write_text(
                "#!/bin/sh\nprintf '%s\\n' \"$@\" >> \"$SUDO_CALL_LOG\"\n",
                encoding="utf-8",
            )
            (bindir / "flock").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
            os.chmod(bindir / "id", 0o755)
            os.chmod(bindir / "sudo", 0o755)
            os.chmod(bindir / "flock", 0o755)
            env = os.environ.copy()
            env["PATH"] = f"{bindir}:{env['PATH']}"
            env["SUDO_CALL_LOG"] = str(call_log)

            result = subprocess.run(
                ["bash", str(AUDIO_INSTALLER), "uninstall"],
                check=True,
                capture_output=True,
                text=True,
                env=env,
            )

            self.assertEqual(
                call_log.read_text(encoding="utf-8").splitlines(),
                [
                    "env",
                    "BC250_PRESERVE_AMDGPU_BOOT_CONFIG=1",
                    str(AUDIO_ROLLBACK),
                    "--all",
                    str(ROOT / "bc250-audio-fix/cleanup-other-slot.sh"),
                    "--skip-current",
                    "env",
                    "BC250_FORCE_GRUB_REGEN=1",
                    str(AUDIO_BOOT_CONFIG),
                    "remove",
                ],
            )
            self.assertIn("build output were preserved", result.stdout)

    def test_aic_uninstall_disables_repair_before_removing_artifacts(self):
        script = AIC_INSTALLER.read_text(encoding="utf-8")
        disable = script.index(
            "systemctl disable --now aic8800-modules.service"
        )
        remove_modules = script.index(
            "for path in /usr/lib/modules/*/updates/aic8800/aic_load_fw.ko"
        )
        self.assertLess(disable, remove_modules)
        self.assertIn(
            'rm -rf "$AIC_DATA_DIR/firmware" "$AIC_DATA_DIR/modules"',
            script,
        )
        self.assertNotIn('rm -rf "$ROOT_SOURCE"', script)
        self.assertIn("persistent source preserved", script)

    def test_aic_boot_defers_firmware_probe_until_persistent_storage(self):
        installer = AIC_INSTALLER.read_text(encoding="utf-8")
        helper = AIC_HELPER.read_text(encoding="utf-8")
        service = AIC_SERVICE.read_text(encoding="utf-8")

        self.assertIn("blacklist aic_load_fw", installer)
        self.assertIn("RequiresMountsFor=/var/lib/bc250-control", service)
        self.assertIn("After=bc250-persistence-recovery.service", service)
        self.assertNotIn("network-online.target", service)
        self.assertIn("usb_device_has_id a69c 8d80", helper)
        self.assertIn("/sys/bus/usb/drivers_probe", helper)
        self.assertIn("wait_for_aic_runtime", helper)
        self.assertIn("did not transition from 8d80 to a bound 8d81 runtime", helper)

    def test_lifecycle_scripts_parse(self):
        subprocess.run(
            [
                "bash",
                "-n",
                str(AIC_INSTALLER),
                str(AUDIO_INSTALLER),
                str(ROOT / "bc250-audio-fix/install.sh"),
                str(AUDIO_BOOT_CONFIG),
                str(ROOT / "bc250-audio-fix/build.sh"),
                str(AUDIO_CLEAN),
                str(AUDIO_ROLLBACK),
                str(AUDIO_PREREQS),
            ],
            check=True,
        )

    def test_audio_build_restores_and_validates_prerequisites(self):
        installer = AUDIO_INSTALLER.read_text(encoding="utf-8")
        builder = (ROOT / "bc250-audio-fix/build.sh").read_text(encoding="utf-8")
        fetcher = (ROOT / "bc250-audio-fix/fetch-sources.sh").read_text(
            encoding="utf-8"
        )
        preparer = (ROOT / "bc250-audio-fix/prepare-kernel.sh").read_text(
            encoding="utf-8"
        )
        environment = (ROOT / "bc250-audio-fix/build-env.sh").read_text(
            encoding="utf-8"
        )
        prerequisites = AUDIO_PREREQS.read_text(encoding="utf-8")

        for entrypoint in (installer, builder, fetcher, preparer):
            self.assertIn('"$HERE/ensure-build-prereqs.sh"', entrypoint)
        self.assertIn("base-devel", prerequisites)
        for tool in ("make", "gcc", "ld", "patch", "pahole", "bc", "zstd"):
            self.assertIn(tool, environment)

    def test_diverged_audio_tree_offers_clean_and_retry(self):
        installer = AUDIO_INSTALLER.read_text(encoding="utf-8")
        builder = (ROOT / "bc250-audio-fix/build.sh").read_text(encoding="utf-8")

        self.assertIn("die_tree_drift", builder)
        self.assertIn("exit 75", builder)
        self.assertIn("Clean the build tree and retry?", installer)
        self.assertIn('"$HERE/clean.sh" "$@"', installer)
        self.assertIn('"$HERE/fetch-sources.sh" "$@"', installer)
        self.assertLess(
            installer.index('"$HERE/clean.sh" "$@"'),
            installer.rindex('"$HERE/fetch-sources.sh" "$@"'),
        )
        self.assertGreaterEqual(builder.count("die_tree_drift \""), 6)

    def test_amdgpu_build_integrates_cyan_skillfish_metrics_patches(self):
        builder = (ROOT / "bc250-audio-fix/build.sh").read_text(encoding="utf-8")
        installer = (ROOT / "bc250-audio-fix/install.sh").read_text(encoding="utf-8")
        rollback = AUDIO_ROLLBACK.read_text(encoding="utf-8")
        patch = METRICS_PATCH.read_text(encoding="utf-8")
        gfxclk_patch = GFXCLK_PATCH.read_text(encoding="utf-8")
        gfx1013_attestation_patch = GFX1013_ATTESTATION_PATCH.read_text(
            encoding="utf-8"
        )
        self.assertIn("bc250-cyan-skillfish-gpu-telemetry.patch", builder)
        self.assertIn("bc250-cyan-skillfish-gfxclk.patch", builder)
        self.assertLess(
            builder.index(str(METRICS_PATCH.name)),
            builder.index(str(GFXCLK_PATCH.name)),
        )
        self.assertNotIn("LEGACY_", builder)
        self.assertIn("METRICS_SOURCE_SHA", builder)
        self.assertIn("GRBM_STATUS__GUI_ACTIVE_MASK", patch)
        self.assertIn("AMDGPU_PP_SENSOR_GPU_LOAD", patch)
        self.assertIn("average_gfx_activity", patch)
        self.assertIn("PPSMC_MSG_GetGfxFrequency", gfxclk_patch)
        self.assertIn("SMU_MSG_GetGfxclkFrequency", gfxclk_patch)
        self.assertIn("cyan_skillfish_get_gfxclk_frequency", gfxclk_patch)
        self.assertIn("return -ERANGE", gfxclk_patch)
        self.assertIn("gpu_metrics->current_gfxclk = gfxclk", gfxclk_patch)
        for name in (
            "0001-gfx1013-mmio-pasid-route.patch",
            "0002-gfx1013-compute-gfxoff-guard.patch",
            "0003-gfx1013-scoped-pasid-type0.patch",
        ):
            self.assertIn(name, builder)
        self.assertIn("d3e6dc062c34d2523db0abe5741d1f5b0dea00d9", builder)
        self.assertIn("DryhoppedIPA/bc250-gfx1013-fix", builder)
        self.assertIn("bc250-gfx1013-attestation.patch", builder)
        self.assertIn("bc250_gfx1013_fix", gfx1013_attestation_patch)
        self.assertIn(".bc250-metrics-fix", installer)
        self.assertIn(".bc250-metrics-fix", rollback)
        self.assertIn(".bc250-gfx1013-fix", installer)
        self.assertIn(".bc250-gfx1013-fix", rollback)
        self.assertIn("amdgpu.gfx1013.attestation", builder)
        self.assertIn("amdgpu.gfx1013.attestation", installer)

    def test_async_compute_scheduler_policy_status_is_verified(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            config = root / "bc250-amdgpu.cfg"
            grub = root / "grub.cfg"
            keep = root / "bc250-amdgpu.conf"
            cmdline = root / "cmdline"
            config.write_text(
                "# BC-250 AMDGPU scheduler policy managed by "
                "bc250-audio-fix/boot-config.sh.\n"
                "# Required by the GFX1013 async-compute queue repair.\n"
                'GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT:-} '
                'amdgpu.sched_policy=2"\n',
                encoding="utf-8",
            )
            grub.write_text(
                "steamenv_boot linux /boot/vmlinuz quiet amdgpu.sched_policy=2\n",
                encoding="utf-8",
            )
            keep.write_text(
                "# Toolkit state preserved by SteamOS atomic updates.\n"
                "# Generated by bc250-update-persistence.sh.\n"
                f"{config}\n"
                "/etc/systemd/system/bc250-persistence-recovery.service\n"
                "/etc/systemd/system/local-fs.target.wants/"
                "bc250-persistence-recovery.service\n"
                "/etc/systemd/system/var-lib-bc250\\x2dcontrol.mount\n"
                "/etc/systemd/system/local-fs.target.wants/"
                "var-lib-bc250\\x2dcontrol.mount\n",
                encoding="utf-8",
            )
            cmdline.write_text(
                "quiet amdgpu.sched_policy=2\n", encoding="utf-8"
            )
            bindir = root / "bin"
            bindir.mkdir()
            stat = bindir / "stat"
            stat.write_text(
                '#!/bin/sh\n[ "$2" = %u ] && { echo 0; exit; }; echo 644\n',
                encoding="utf-8",
            )
            stat.chmod(0o755)
            env = os.environ.copy()
            env.update(
                {
                    "SCHED_CONFIG": str(config),
                    "GRUB_DEFAULT": str(root / "default-grub"),
                    "GRUB_CFG": str(grub),
                    "PROC_CMDLINE": str(cmdline),
                    "AMDGPU_KEEP_FILE": str(keep),
                    "PATH": f"{bindir}:{env['PATH']}",
                }
            )

            result = subprocess.run(
                ["bash", str(AUDIO_BOOT_CONFIG), "status"],
                check=True,
                capture_output=True,
                text=True,
                env=env,
            )

            self.assertIn("configured and active", result.stdout)

            grub.write_text(
                "steamenv_boot linux /boot/vmlinuz quiet amdgpu.sched_policy=2\n"
                "steamenv_boot linux /boot/vmlinuz-fallback quiet\n",
                encoding="utf-8",
            )
            invalid = subprocess.run(
                ["bash", str(AUDIO_BOOT_CONFIG), "status"],
                capture_output=True,
                text=True,
                env=env,
            )

            self.assertNotEqual(invalid.returncode, 0)
            self.assertIn("incomplete", invalid.stdout)

    def test_async_compute_install_and_rollback_manage_boot_policy(self):
        installer = (ROOT / "bc250-audio-fix/install.sh").read_text(
            encoding="utf-8"
        )
        rollback = AUDIO_ROLLBACK.read_text(encoding="utf-8")
        cleanup = (ROOT / "bc250-audio-fix/cleanup-other-slot.sh").read_text(
            encoding="utf-8"
        )

        self.assertIn('"$BOOT_CONFIG" install', installer)
        self.assertIn('"$BOOT_CONFIG" remove', rollback)
        self.assertIn("BC250_SKIP_GRUB_REGEN=1", cleanup)
        self.assertIn("amdgpu.sched_policy=2", installer)


if __name__ == "__main__":
    unittest.main()
