import json
import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
POWER = ROOT / "bc250-power.sh"


def run_sourced(body: str, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [
            "bash",
            "-c",
            'script=$1; shift; args=("$@"); set -- help; '
            'REAL_HOME=/tmp FIXES_REPO_DIR=/tmp source "$script" >/dev/null; '
            'set -- "${args[@]}"; ' + body,
            "_",
            str(POWER),
            *args,
        ],
        capture_output=True,
        text=True,
    )


class CpuSmtTests(unittest.TestCase):
    def test_disable_applies_live_before_enabling_boot_service(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            control = root / "control"
            unit = root / "system/bc250-disable-smt.service"
            wants = root / "wants"
            keep = root / "keep.conf"
            log = root / "actions.log"
            control.write_text("on\n", encoding="ascii")
            wants.mkdir()

            result = run_sourced(
                'SMT_CONTROL=$1; SMT_UNIT=$2; SYSTEMD_WANTS_DIR=$3; POWER_KEEP_FILE=$4; LOG=$5; '
                'require_root() { :; }; unlock_rootfs() { :; }; relock_rootfs() { :; }; chown() { :; }; '
                'tee() { local value; IFS= read -r value; printf "%s\\n" "$value" > "$1"; printf "live:%s\\n" "$value" >> "$LOG"; }; '
                'systemctl() { case "$1" in is-enabled) [[ -L "$SYSTEMD_WANTS_DIR/$SMT_SVC" ]] && printf "enabled\\n";; '
                'enable) ln -s "$SMT_UNIT" "$SYSTEMD_WANTS_DIR/$SMT_SVC"; printf "boot:enable\\n" >> "$LOG";; '
                'disable) rm -f "$SYSTEMD_WANTS_DIR/$SMT_SVC";; daemon-reload) :;; esac; }; '
                'install_update_persistence() { printf "%s\\n" "# Toolkit state preserved by SteamOS atomic updates." '
                '"# Generated by bc250-update-persistence.sh." /etc/systemd/system/bc250-disable-smt.service '
                '/etc/systemd/system/multi-user.target.wants/bc250-disable-smt.service > "$POWER_KEEP_FILE"; '
                'printf "boot:persist\\n" >> "$LOG"; }; '
                'cpu_smt_set disabled; cpu_smt_status_json',
                str(control),
                str(unit),
                str(wants),
                str(keep),
                str(log),
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(control.read_text(encoding="ascii"), "off\n")
            self.assertIn("echo off | /usr/bin/tee", unit.read_text(encoding="ascii"))
            self.assertEqual(
                log.read_text(encoding="ascii").splitlines(),
                ["live:off", "boot:enable", "boot:persist"],
            )
            status = json.loads(result.stdout.splitlines()[-1])
            self.assertTrue(status["configuredDisabled"])
            self.assertTrue(status["liveDisabled"])
            self.assertTrue(status["protected"])

    def test_enable_applies_live_and_removes_owned_boot_unit(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            control = root / "control"
            unit = root / "system/bc250-disable-smt.service"
            wants = root / "wants"
            control.write_text("off\n", encoding="ascii")
            unit.parent.mkdir()
            wants.mkdir()

            result = run_sourced(
                'SMT_CONTROL=$1; SMT_UNIT=$2; SYSTEMD_WANTS_DIR=$3; '
                'render_cpu_smt_unit > "$SMT_UNIT"; ln -s "$SMT_UNIT" "$SYSTEMD_WANTS_DIR/$SMT_SVC"; '
                'require_root() { :; }; unlock_rootfs() { :; }; relock_rootfs() { :; }; '
                'tee() { local value; IFS= read -r value; printf "%s\\n" "$value" > "$1"; }; '
                'systemctl() { case "$1" in is-enabled) printf "enabled\\n";; disable) rm -f "$SYSTEMD_WANTS_DIR/$SMT_SVC";; daemon-reload) :;; esac; }; '
                'cpu_smt_set enabled',
                str(control),
                str(unit),
                str(wants),
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(control.read_text(encoding="ascii"), "on\n")
            self.assertFalse(unit.exists())
            self.assertFalse((wants / "bc250-disable-smt.service").exists())

    def test_foreign_boot_unit_is_not_overwritten(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            control = root / "control"
            unit = root / "bc250-disable-smt.service"
            control.write_text("on\n", encoding="ascii")
            unit.write_text("operator managed\n", encoding="ascii")

            result = run_sourced(
                'SMT_CONTROL=$1; SMT_UNIT=$2; require_root() { :; }; '
                'cpu_smt_set disabled',
                str(control),
                str(unit),
            )

            self.assertNotEqual(result.returncode, 0)
            self.assertEqual(control.read_text(encoding="ascii"), "on\n")
            self.assertEqual(unit.read_text(encoding="ascii"), "operator managed\n")


if __name__ == "__main__":
    unittest.main()
