import os
import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "hdmi-ac3/hdmi-ac3.sh"


class HdmiAc3Tests(unittest.TestCase):
    def render_managed_files(self, root: Path):
        udev = root / "91-bc250-hdmi-ac3.rules"
        wireplumber = root / "90-bc250-hdmi-ac3.conf"
        keep = root / "bc250-ac3.conf"
        subprocess.run(
            [
                "bash",
                "-c",
                'script=$1; udev=$2; wp=$3; set -- help; source "$script" >/dev/null; '
                'udev_rule_content > "$udev"; wireplumber_content > "$wp"',
                "_",
                str(SCRIPT),
                str(udev),
                str(wireplumber),
            ],
            check=True,
        )
        keep.write_text(
            "# Toolkit state preserved by SteamOS atomic updates.\n"
            "# Generated by bc250-update-persistence.sh.\n"
            f"{udev}\n",
            encoding="utf-8",
        )
        return udev, wireplumber, keep

    def test_status_recognizes_exact_managed_configuration(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            udev, wireplumber, keep = self.render_managed_files(root)
            env = os.environ.copy()
            env["UDEV_RULE"] = str(udev)
            env["WP_CONF"] = str(wireplumber)
            env["KEEP_FILE"] = str(keep)
            result = subprocess.run(
                ["bash", str(SCRIPT), "status"],
                check=True,
                capture_output=True,
                text=True,
                env=env,
            )
            self.assertIn("udev rule: installed", result.stdout)
            self.assertIn("WirePlumber config: installed", result.stdout)
            self.assertIn("update persistence: installed", result.stdout)
            self.assertIn("state: configured", result.stdout)

    def test_foreign_configuration_is_incomplete_and_not_owned(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            udev = root / "rule"
            wp = root / "config"
            udev.write_text("operator rule\n", encoding="utf-8")
            wp.write_text("operator config\n", encoding="utf-8")
            env = os.environ.copy()
            env["UDEV_RULE"] = str(udev)
            env["WP_CONF"] = str(wp)
            result = subprocess.run(
                ["bash", str(SCRIPT), "status"],
                capture_output=True,
                text=True,
                env=env,
            )
            self.assertEqual(result.returncode, 1)
            self.assertIn("udev rule: foreign", result.stdout)
            self.assertIn("WirePlumber config: foreign", result.stdout)
            self.assertIn("state: incomplete", result.stdout)

    def test_profile_settings_and_revert_guards_are_present(self):
        source = SCRIPT.read_text(encoding="utf-8")
        self.assertIn('device.profile-set = "hdmi-ac3.conf"', source)
        self.assertIn("session.suspend-timeout-seconds = 3600", source)
        self.assertIn("api.alsa.start-delay = 1536", source)
        self.assertIn('ATTRS{vendor}=="0x1002"', source)
        self.assertIn('ATTRS{device}=="0x1640"', source)
        self.assertIn("preflight_managed_file", source)
        self.assertIn("output:hdmi-stereo", source)
        self.assertIn('bash "$PERSISTENCE_SH" install ac3', source)
        self.assertIn('bash "$PERSISTENCE_SH" remove ac3', source)
        self.assertIn("rollback_install", source)
        self.assertIn('index($2, card_path)', source)
        self.assertIn("wait_for_hdmi_card", source)
        self.assertIn("finish_rootfs", source)

    def test_activation_failure_removes_new_user_config_and_rolls_back_system(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            wp = root / "wireplumber/config.conf"
            calls = root / "calls"
            env = os.environ.copy()
            env.update(
                {
                    "WP_CONF": str(wp),
                    "UDEV_RULE": str(root / "udev.rules"),
                    "KEEP_FILE": str(root / "keep.conf"),
                    "CALLS": str(calls),
                }
            )
            result = subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; set -- help; source "$script" >/dev/null; '
                    'require_runtime() { :; }; find_hdmi_card() { echo card; }; '
                    'sudo() { printf "%s\\n" "$*" >> "$CALLS"; }; '
                    'restart_wireplumber() { return 1; }; install_ac3',
                    "_",
                    str(SCRIPT),
                ],
                capture_output=True,
                text=True,
                env=env,
            )
            self.assertNotEqual(result.returncode, 0)
            self.assertFalse(wp.exists())
            self.assertEqual(
                calls.read_text(encoding="utf-8").splitlines(),
                [
                    f"bash {SCRIPT} install-system",
                    f"bash {SCRIPT} rollback-system 0 0",
                ],
            )
            self.assertIn("previous HDMI audio configuration was restored", result.stdout)


if __name__ == "__main__":
    unittest.main()
