import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STORAGE = ROOT / "bc250-storage.sh"
PERSISTENCE = ROOT / "bc250-update-persistence.sh"
DESKTOP_INSTALL = ROOT / "desktop-control" / "install.sh"
DESKTOP_REPAIR = ROOT / "desktop-control" / "bc250-desktop-control-repair"
SHARED_INSTALL = ROOT / "desktop-control" / "shared-service-install.sh"
DESKTOP_TEMPLATES = ROOT / "desktop-control" / "templates"


def render(name: str) -> str:
    return subprocess.run(
        ["bash", str(STORAGE), "render", name],
        check=True,
        capture_output=True,
        text=True,
    ).stdout


class PersistenceUnitTests(unittest.TestCase):
    def test_component_keep_list_removal_preserves_legacy_and_storage(self):
        with tempfile.TemporaryDirectory() as directory:
            keep_dir = Path(directory)
            owned = keep_dir / "bc250-compute.conf"
            legacy = keep_dir / "bc250-steamos.conf"
            storage = keep_dir / "bc250-storage.conf"
            owned.write_text(
                "# Toolkit state preserved by SteamOS atomic updates.\n"
                "# Generated by bc250-update-persistence.sh.\n"
                "/etc/bc250-cu-live-manager.conf\n",
                encoding="utf-8",
            )
            legacy.write_text("/etc/custom-legacy-state\n", encoding="utf-8")
            storage.write_text("storage infrastructure\n", encoding="utf-8")

            result = subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; keep=$2; set -- help; source "$script" >/dev/null; '
                    'require_root() { :; }; KEEP_DIR=$keep; '
                    'LEGACY_KEEP_FILE="$keep/bc250-steamos.conf"; '
                    "remove_keep_list compute",
                    "_",
                    str(PERSISTENCE),
                    str(keep_dir),
                ],
                check=True,
                capture_output=True,
                text=True,
            )

            self.assertFalse(owned.exists())
            self.assertTrue(legacy.exists())
            self.assertTrue(storage.exists())
            self.assertIn("Legacy wholesale keep list preserved", result.stdout)

    def test_keep_list_remove_all_preflights_before_deleting(self):
        with tempfile.TemporaryDirectory() as directory:
            keep_dir = Path(directory)
            owned = keep_dir / "bc250-compute.conf"
            foreign = keep_dir / "bc250-power.conf"
            owned.write_text(
                "# Toolkit state preserved by SteamOS atomic updates.\n"
                "# Generated by bc250-update-persistence.sh.\n",
                encoding="utf-8",
            )
            foreign.write_text("/etc/operator-owned-state\n", encoding="utf-8")

            result = subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; keep=$2; set -- help; source "$script" >/dev/null; '
                    'require_root() { :; }; KEEP_DIR=$keep; '
                    'LEGACY_KEEP_FILE="$keep/bc250-steamos.conf"; '
                    "remove_keep_list all",
                    "_",
                    str(PERSISTENCE),
                    str(keep_dir),
                ],
                capture_output=True,
                text=True,
            )

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("unrecognized keep list", result.stderr)
            self.assertTrue(owned.exists())
            self.assertTrue(foreign.exists())

    def test_storage_dependency_probe_is_machine_readable(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            systemd = root / "systemd"
            keep = root / "keep"
            data = root / "data"
            systemd.mkdir()
            keep.mkdir()
            data.mkdir()
            (systemd / "bc250-control.service").write_text("unit\n", encoding="utf-8")
            (keep / "bc250-compute.conf").write_text("keep\n", encoding="utf-8")

            blocked = subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; systemd=$2; keep=$3; data=$4; set -- help; '
                    'source "$script" >/dev/null; SYSTEMD_DIR=$systemd; '
                    'ATOMIC_KEEP_DIR=$keep; ROOT_DIR=$data; '
                    'systemctl() { return 1; }; can_uninstall',
                    "_",
                    str(STORAGE),
                    str(systemd),
                    str(keep),
                    str(data),
                ],
                capture_output=True,
                text=True,
            )
            (systemd / "bc250-control.service").unlink()
            (keep / "bc250-compute.conf").unlink()
            ready = subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; systemd=$2; keep=$3; data=$4; set -- help; '
                    'source "$script" >/dev/null; SYSTEMD_DIR=$systemd; '
                    'ATOMIC_KEEP_DIR=$keep; ROOT_DIR=$data; '
                    'systemctl() { return 1; }; can_uninstall',
                    "_",
                    str(STORAGE),
                    str(systemd),
                    str(keep),
                    str(data),
                ],
                check=True,
                capture_output=True,
                text=True,
            )

            self.assertEqual(blocked.returncode, 1)
            self.assertEqual(
                blocked.stdout.splitlines(),
                ["service:bc250-control.service", "persistence:compute"],
            )
            self.assertEqual(ready.stdout.strip(), "ready")

    def test_ram_payload_blocks_storage_uninstall(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "bin").mkdir()
            (root / "bin/bc250memcfg").write_text("tool\n", encoding="utf-8")
            systemd = root / "systemd"
            keep = root / "keep"
            systemd.mkdir()
            keep.mkdir()
            result = subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; data=$2; systemd=$3; keep=$4; set -- help; '
                    'source "$script" >/dev/null; ROOT_DIR=$data; SYSTEMD_DIR=$systemd; '
                    'ATOMIC_KEEP_DIR=$keep; systemctl() { return 1; }; can_uninstall',
                    "_",
                    str(STORAGE),
                    str(root),
                    str(systemd),
                    str(keep),
                ],
                capture_output=True,
                text=True,
            )

            self.assertEqual(result.returncode, 1)
            self.assertEqual(result.stdout.strip(), "component:ram")

    def test_ram_keep_list_contains_owned_ttm_fragment(self):
        with tempfile.TemporaryDirectory() as directory:
            keep = Path(directory)
            result = subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; keep=$2; set -- help; source "$script" >/dev/null; '
                    'require_root() { :; }; install_storage() { :; }; KEEP_DIR=$keep; '
                    'LEGACY_KEEP_FILE="$keep/bc250-steamos.conf"; install_keep_list ram',
                    "_",
                    str(PERSISTENCE),
                    str(keep),
                ],
                check=True,
                capture_output=True,
                text=True,
            )
            payload = (keep / "bc250-ram.conf").read_text(encoding="utf-8")

            self.assertIn("Atomic-update keep list installed", result.stdout)
            self.assertIn("/etc/default/grub.d/bc250-ttm.cfg", payload)
            self.assertIn("bc250-persistence-recovery.service", payload)

    def test_amdgpu_keep_list_contains_scheduler_fragment(self):
        with tempfile.TemporaryDirectory() as directory:
            keep = Path(directory)
            result = subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; keep=$2; set -- help; source "$script" >/dev/null; '
                    'require_root() { :; }; install_storage() { :; }; KEEP_DIR=$keep; '
                    'LEGACY_KEEP_FILE="$keep/bc250-steamos.conf"; '
                    "install_keep_list amdgpu",
                    "_",
                    str(PERSISTENCE),
                    str(keep),
                ],
                check=True,
                capture_output=True,
                text=True,
            )
            payload = (keep / "bc250-amdgpu.conf").read_text(encoding="utf-8")

            self.assertIn("Atomic-update keep list installed", result.stdout)
            self.assertIn("/etc/default/grub.d/bc250-amdgpu.cfg", payload)

    def test_ac3_keep_list_contains_udev_profile_selector(self):
        with tempfile.TemporaryDirectory() as directory:
            keep = Path(directory)
            subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; keep=$2; set -- help; source "$script" >/dev/null; '
                    'require_root() { :; }; install_storage() { :; }; KEEP_DIR=$keep; '
                    'LEGACY_KEEP_FILE="$keep/bc250-steamos.conf"; install_keep_list ac3',
                    "_",
                    str(PERSISTENCE),
                    str(keep),
                ],
                check=True,
                capture_output=True,
                text=True,
            )
            payload = (keep / "bc250-ac3.conf").read_text(encoding="utf-8")
            self.assertIn("/etc/udev/rules.d/91-bc250-hdmi-ac3.rules", payload)
            self.assertIn("bc250-persistence-recovery.service", payload)

    def test_swap_keep_list_contains_generator_and_disk_units(self):
        with tempfile.TemporaryDirectory() as directory:
            keep = Path(directory)
            subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; keep=$2; set -- help; source "$script" >/dev/null; '
                    'require_root() { :; }; install_storage() { :; }; KEEP_DIR=$keep; '
                    'LEGACY_KEEP_FILE="$keep/bc250-steamos.conf"; install_keep_list swap',
                    "_",
                    str(PERSISTENCE),
                    str(keep),
                ],
                check=True,
                capture_output=True,
                text=True,
            )
            payload = (keep / "bc250-swap.conf").read_text(encoding="utf-8")
            self.assertIn("zram-generator.conf.d/90-bc250-swap.conf", payload)
            self.assertIn("tmpfiles.d/00-bc250-zswap.conf", payload)
            self.assertIn("bc250-zswap-setup.service", payload)
            self.assertIn("swapfile.swap", payload)
            self.assertIn("bc250-persistence-recovery.service", payload)

    def test_storage_uninstall_preserves_backing_and_stops_recovery(self):
        with tempfile.TemporaryDirectory() as directory:
            result = subprocess.run(
                [
                    "bash",
                    "-c",
                    r'''
script=$1
base=$2
set -- help
source "$script" >/dev/null
require_root() { :; }
validate_storage_paths() { :; }
secure_file() { :; }
secure_directory() { :; }
mountpoint() { return 1; }
systemctl() {
    printf '%s\n' "$*" >> "$SYSTEMCTL_LOG"
    if [[ "$1" == is-active ]]; then
        [[ "$3" == "$RECOVERY_NAME" ]]
        return
    fi
}
ROOT_DIR="$base/root"
BACKING_DIR="$base/backing"
SYSTEMD_DIR="$base/systemd"
ATOMIC_KEEP_DIR="$base/keep"
UNIT_PATH="$SYSTEMD_DIR/$UNIT_NAME"
UNIT_WANTS="$SYSTEMD_DIR/local-fs.target.wants/$UNIT_NAME"
RECOVERY_PATH="$SYSTEMD_DIR/$RECOVERY_NAME"
RECOVERY_WANTS="$SYSTEMD_DIR/local-fs.target.wants/$RECOVERY_NAME"
RECOVERY_HELPER="$BACKING_DIR/helper/bc250-storage.sh"
KEEP_PATH="$ATOMIC_KEEP_DIR/bc250-storage.conf"
SYSTEMCTL_LOG="$base/systemctl.log"
mkdir -p "$ROOT_DIR" "$BACKING_DIR/helper" \
    "$(dirname "$UNIT_WANTS")" "$ATOMIC_KEEP_DIR"
printf 'payload\n' > "$BACKING_DIR/data"
printf 'helper\n' > "$RECOVERY_HELPER"
render_mount_unit > "$UNIT_PATH"
render_recovery_unit > "$RECOVERY_PATH"
render_keep_file > "$KEEP_PATH"
ln -s "../$UNIT_NAME" "$UNIT_WANTS"
ln -s "../$RECOVERY_NAME" "$RECOVERY_WANTS"
uninstall_storage
[[ -d "$BACKING_DIR" && -f "$BACKING_DIR/data" ]]
[[ ! -e "$ROOT_DIR" && ! -e "$UNIT_PATH" && ! -e "$RECOVERY_PATH" ]]
grep -Fxq "stop $RECOVERY_NAME" "$SYSTEMCTL_LOG"
grep -Fxq "daemon-reload" "$SYSTEMCTL_LOG"
''',
                    "_",
                    str(STORAGE),
                    directory,
                ],
                check=True,
                capture_output=True,
                text=True,
            )
            self.assertIn("backing data preserved", result.stdout)

    def test_storage_lifecycle_has_destructive_guards_and_safe_order(self):
        source = STORAGE.read_text(encoding="utf-8")
        uninstall = source[source.index("uninstall_storage()") :]
        self.assertLess(
            uninstall.index('rm -f "$UNIT_WANTS" "$RECOVERY_WANTS"'),
            uninstall.index('systemctl stop "$UNIT_NAME"'),
        )
        self.assertLess(
            uninstall.index('systemctl stop "$UNIT_NAME"'),
            uninstall.index('umount "$ROOT_DIR"'),
        )
        self.assertLess(
            uninstall.index('umount "$ROOT_DIR"'),
            uninstall.index('systemctl stop "$RECOVERY_NAME"'),
        )
        self.assertIn("expected_mount_active", uninstall)
        self.assertIn("require_no_dependencies \"uninstall storage\"", source)
        self.assertIn("require_no_dependencies \"purge storage\"", source)
        self.assertIn("validate_storage_paths", source)
        self.assertIn('case "$target" in', source)
        self.assertIn('done < <(findmnt -rn -o FSROOT,TARGET)', source)
        self.assertIn('find "$BACKING_DIR" ! -uid 0', source)

    def test_storage_blocks_on_swap_state_without_keep_list(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            result = subprocess.run(
                [
                    "bash",
                    "-c",
                    'script=$1; root=$2; set -- help; source "$script" >/dev/null; '
                    'ROOT_DIR="$root/data"; SYSTEMD_DIR="$root/systemd"; '
                    'ATOMIC_KEEP_DIR="$root/keep"; mkdir -p "$ROOT_DIR/swap"; '
                    'touch "$ROOT_DIR/swap/install.conf"; systemctl() { return 1; }; '
                    'can_uninstall',
                    "_",
                    str(STORAGE),
                    str(root),
                ],
                capture_output=True,
                text=True,
            )
            self.assertEqual(result.returncode, 1)
            self.assertEqual(result.stdout.strip(), "component:swap")

    def test_recovery_bootstraps_from_home_before_local_filesystems(self):
        unit = render("recovery")
        self.assertIn("DefaultDependencies=no", unit)
        self.assertIn("RequiresMountsFor=/home", unit)
        self.assertIn("After=home.mount", unit)
        self.assertIn(
            "Before=var-lib-bc250\\x2dcontrol.mount local-fs.target", unit
        )
        self.assertIn(
            "ExecStart=/home/.steamos/offload/var/lib/bc250-control/helper/"
            "bc250-storage.sh repair-infrastructure",
            unit,
        )
        self.assertNotIn("/etc/previous", unit)
        self.assertNotIn("recover all", unit)
        self.assertNotIn("PrivateMounts=", unit)
        self.assertNotIn("PrivateTmp=", unit)
        self.assertNotIn("ProtectHome=", unit)
        self.assertNotIn("ProtectKernel", unit)
        self.assertNotIn("ProtectControlGroups=", unit)

    def test_mount_waits_for_recovery(self):
        unit = render("mount")
        self.assertIn("Requires=bc250-persistence-recovery.service", unit)
        self.assertIn(
            "After=home.mount bc250-persistence-recovery.service", unit
        )
        self.assertIn("What=/home/.steamos/offload/var/lib/bc250-control", unit)
        self.assertIn("Where=/var/lib/bc250-control", unit)
        self.assertIn("Options=bind", unit)

    def test_keep_list_retains_complete_bootstrap(self):
        keep = render("keep")
        for path in (
            "/etc/systemd/system/bc250-persistence-recovery.service",
            "/etc/systemd/system/local-fs.target.wants/"
            "bc250-persistence-recovery.service",
            "/etc/systemd/system/var-lib-bc250\\x2dcontrol.mount",
            "/etc/systemd/system/local-fs.target.wants/"
            "var-lib-bc250\\x2dcontrol.mount",
        ):
            self.assertIn(path, keep)

    def test_generated_services_do_not_order_after_their_target(self):
        for relative in ("bc250-power.sh", "bc250-cec.sh"):
            source = (ROOT / relative).read_text(encoding="utf-8")
            self.assertNotIn("After=multi-user.target", source)

    def test_governor_and_restore_require_bootstrap(self):
        source = (ROOT / "bc250-power.sh").read_text(encoding="utf-8")
        self.assertIn("Requires=$RECOVERY_SVC", source)
        self.assertIn("Requires=$RECOVERY_SVC $GOV_SVC", source)
        self.assertIn(
            "After=$RECOVERY_SVC bc250-cu-live-manager.service", source
        )
        self.assertIn(
            "Conflicts=cyan-skillfish-governor.service "
            "cyan-skillfish-governor-tt.service oberon-governor.service",
            source,
        )
        self.assertIn("bc250-core-unlock.service", source)
        storage = (ROOT / "bc250-storage.sh").read_text(encoding="utf-8")
        self.assertIn("bc250-core-unlock.service", storage)

    def test_core_unlock_is_attributed_guarded_and_removable(self):
        helper = (ROOT / "core-unlock" / "bc250-unlock-cores.py").read_text(
            encoding="utf-8"
        )
        notes = (ROOT / "core-unlock" / "README.md").read_text(encoding="utf-8")
        power = (ROOT / "bc250-power.sh").read_text(encoding="utf-8")
        self.assertIn("rw-r-r-0644/bc250-core-unlock", notes)
        self.assertIn("87ec098", helper)
        self.assertIn("fcntl.LOCK_EX", helper)
        self.assertIn('CORE_UNLOCK_LOCK="/run/lock/bc250-core-unlock.lock"', power)
        self.assertIn("CORE_UNLOCK_LIFECYCLE_LOCK=", power)
        self.assertIn("core_unlock_lifecycle_lock", power)
        self.assertIn("reboot-loop guard", helper)
        self.assertIn("Before=$OC_SVC $GOV_SVC", power)
        self.assertIn("core_unlock_uninstall()", power)
        enable = power[
            power.index("core_unlock_enable()") : power.index(
                "core_unlock_status()", power.index("core_unlock_enable()")
            )
        ]
        self.assertIn("verify-unlocked", enable)
        self.assertNotIn("core_unlock_test", enable)
        self.assertLess(enable.index("verify-unlocked"), enable.index("systemctl enable"))
        test = power[
            power.index("core_unlock_test()") : power.index(
                "core_unlock_enable()", power.index("core_unlock_test()")
            )
        ]
        self.assertNotIn("systemctl enable", test)
        self.assertNotIn("install_update_persistence", test)

        efi_source = (ROOT / "core-unlock" / "bc250-unlock-cores-efi.c").read_text(
            encoding="utf-8"
        )
        self.assertIn("BC250CoreUnlockAttempt", efi_source)
        self.assertIn("0x8000000000000000ULL", efi_source)
        self.assertIn("CORE_UNLOCK_EFI_HEADER_LICENSE", power)
        self.assertIn("efi_transaction_rollback", power)
        self.assertIn("remove_core_unlock_efi", power)

    def test_acpi_persistence_targets_active_steamos_grub_config(self):
        source = (ROOT / "bc250-power.sh").read_text(encoding="utf-8")
        persistence = (ROOT / "bc250-update-persistence.sh").read_text(
            encoding="utf-8"
        )
        self.assertIn('GRUB_CFG="/efi/EFI/steamos/grub.cfg"', source)
        self.assertIn(
            'GRUB_ACPI_DEFAULT="/etc/default/grub.d/bc250-acpi.cfg"', source
        )
        self.assertNotIn("/boot/grub/grub.cfg", source)
        self.assertIn("/etc/default/grub.d/bc250-acpi.cfg", persistence)
        self.assertIn("/etc/default/grub.d/bc250-cpu-mitigations.cfg", persistence)
        self.assertIn("current_os_build > \"\\$READY_MARKER\"", source)
        self.assertIn("installed - boot repair needed", source)
        self.assertIn(
            "After=$RECOVERY_SVC local-fs.target steamos-post-update.service", source
        )

    def test_acpi_bootstraps_packaged_steamos_trust_before_installing_cpio(self):
        source = (ROOT / "bc250-power.sh").read_text(encoding="utf-8")
        for expected in (
            "/usr/share/pacman/keyrings/$keyring.gpg",
            "pacman-key --init",
            "pacman-key --populate",
        ):
            self.assertIn(expected, source)
        acpi = source.index("ensure_acpi_build_tools()")
        populate = source.index("prepare_pacman_keyring", acpi)
        install = source.index('pacman -Sy --noconfirm --needed "${packages[@]}"', acpi)
        self.assertLess(populate, install)
        self.assertIn("packages+=(acpica)", source)
        self.assertNotIn("pacman-key --refresh-keys", source)
        self.assertNotIn("SigLevel = Never", source)

    def test_cpu_oc_apply_prefers_the_latest_staged_detection(self):
        source = (ROOT / "bc250-power.sh").read_text(encoding="utf-8")
        apply_section = source[
            source.index("oc_apply()") : source.index("oc_enable()")
        ]
        staged = apply_section.index('local conf="$OC_STAGE_CONF"')
        installed = apply_section.index('conf="$OC_CONF"')
        self.assertLess(staged, installed)

    def test_cpu_oc_configs_are_recovered_validated_and_copied_atomically(self):
        source = (ROOT / "bc250-power.sh").read_text(encoding="utf-8")
        self.assertIn('clean = data.rstrip(b"\\0")', source)
        self.assertIn('oc_prepare_config "$conf"', source)
        self.assertIn('oc_atomic_copy "$OC_STAGE_CONF" "$OC_CONF"', source)
        self.assertNotIn('cp -f "$OC_STAGE_CONF" "$OC_CONF"', source)

        detector = (ROOT / "smu-oc-patches/bc250_detect.py").read_text(
            encoding="utf-8"
        )
        self.assertIn("tempfile.mkstemp(", detector)
        self.assertIn("os.fsync(stream.fileno())", detector)
        self.assertIn("os.replace(temporary, path)", detector)

        prepare_start = source.index("import configparser", source.index("oc_prepare_config()"))
        prepare_end = source.index("\nPY\n}", prepare_start)
        prepare_script = source[prepare_start:prepare_end]
        with tempfile.TemporaryDirectory() as directory:
            profile = Path(directory) / "overclock.conf"
            expected = (
                b"[overclock]\nfrequency = 3800\nscale = -32\n"
                b"max_temperature = 90\n\n"
            )
            profile.write_bytes(expected + b"\0" * 61)
            result = subprocess.run(
                [sys.executable, "-", str(profile)],
                input=prepare_script,
                text=True,
                capture_output=True,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(profile.read_bytes(), expected)
            self.assertIn("Recovered interrupted CPU OC config write", result.stderr)

    def test_decky_cpu_actions_do_not_migrate_legacy_wifi_from_minimal_payload(self):
        storage = (ROOT / "bc250-storage.sh").read_text(encoding="utf-8")
        backend = (ROOT / "backend/bc250_control/backend.py").read_text(
            encoding="utf-8"
        )
        migration = storage[
            storage.index("migrate_aic_helper()") : storage.index("install_storage()")
        ]
        self.assertIn("BC250_STORAGE_SKIP_LEGACY_AIC", migration)
        self.assertGreaterEqual(
            backend.count('"BC250_STORAGE_SKIP_LEGACY_AIC": "1"'), 2
        )

    def test_storage_help_documents_menu_and_sudo_prompt(self):
        result = subprocess.run(
            ["bash", str(STORAGE), "help"],
            check=True,
            capture_output=True,
            text=True,
        )
        self.assertIn("interactive menu", result.stdout)
        self.assertIn("confirmation before invoking sudo", result.stdout)
        source = STORAGE.read_text(encoding="utf-8")
        self.assertIn("Continue with sudo? [y/N]", source)
        self.assertIn('sudo bash "$SELF" "$@"', source)
        self.assertIn(
            'Repair boot infrastructure|$(infrastructure_badge)|', source
        )
        self.assertIn('log "Boot infrastructure is healthy."', source)

    def test_desktop_service_is_isolated_root_dbus_service(self):
        unit = (DESKTOP_TEMPLATES / "bc250-control.service").read_text(
            encoding="utf-8"
        )
        self.assertIn("Type=dbus", unit)
        self.assertIn("BusName=io.github.keyboardspecialist.BC250Control1", unit)
        self.assertIn(
            "ExecStart=/usr/bin/python3 -I /var/lib/bc250-control/desktop/"
            "bc250-control-service",
            unit,
        )
        self.assertIn("User=root", unit)
        self.assertIn("Requires=bc250-desktop-control-repair.service", unit)
        self.assertNotIn("NoNewPrivileges=", unit)
        self.assertNotIn("RestrictSUIDSGID=", unit)

    def test_desktop_dbus_policy_defers_client_authorization_to_service(self):
        policy = (
            DESKTOP_TEMPLATES
            / "io.github.keyboardspecialist.BC250Control1.conf"
        ).read_text(encoding="utf-8")
        self.assertIn('<policy user="root">', policy)
        self.assertIn(
            '<allow own="io.github.keyboardspecialist.BC250Control1"/>',
            policy,
        )
        self.assertIn(
            '<allow send_destination="io.github.keyboardspecialist.BC250Control1"/>',
            policy,
        )
        self.assertNotIn("send_interface", policy)

    def test_governor_dbus_policy_is_root_only(self):
        power = (ROOT / "bc250-power.sh").read_text(encoding="utf-8")
        self.assertIn('<policy user="root">', power)
        self.assertEqual(power.count('<policy context="default">'), 1)
        self.assertNotIn('<allow send_interface=', power)
        self.assertIn(
            "grep -q '<policy context=\"default\">' \"$DBUS_POLICY\"",
            power,
        )

    def test_desktop_payload_and_readonly_handling_are_persistent(self):
        installer = DESKTOP_INSTALL.read_text(encoding="utf-8")
        shared = SHARED_INSTALL.read_text(encoding="utf-8")
        repair = DESKTOP_REPAIR.read_text(encoding="utf-8")
        self.assertIn("/var/lib/bc250-control/.desktop-stage.", shared)
        self.assertIn("$SHARED_STAGE/py_modules/bc250_control_service", shared)
        self.assertIn("$SHARED_STAGE/py_modules/bc250_control", shared)
        self.assertIn("$SHARED_STAGE/py_modules/tomli", shared)
        self.assertIn("$SHARED_STAGE/py_modules/dbus_next", shared)
        self.assertIn("kpackagetool6 --type Plasma/Applet --upgrade", installer)
        self.assertNotIn("--show-info", installer)
        self.assertIn('plugin.get("Id") != sys.argv[2]', installer)
        self.assertIn(
            'metadata.get("X-Plasma-API-Minimum-Version") != "6.0"',
            installer,
        )
        self.assertIn("SHARED_PAYLOAD_SWAPPED=1", shared)
        self.assertIn("trap shared_restore_uninstall_readonly EXIT", shared)
        self.assertIn(
            "state=$(/usr/bin/steamos-readonly status 2>&1) || true",
            shared,
        )
        self.assertIn("READONLY_CHANGED=1", repair)
        self.assertIn("trap restore_readonly EXIT", repair)
        self.assertIn(
            "state=$(/usr/bin/steamos-readonly status 2>&1) || true",
            repair,
        )
        self.assertIn(
            "if [[ $READONLY_CHANGED -eq 1 ]]; then\n"
            "        /usr/bin/steamos-readonly enable",
            repair,
        )

    def test_isolated_entrypoint_imports_staged_service_and_dependencies(self):
        with tempfile.TemporaryDirectory() as directory:
            payload = Path(directory) / "desktop"
            modules = payload / "py_modules"
            modules.mkdir(parents=True)
            shutil.copy2(
                ROOT / "desktop-control" / "service" / "bc250-control-service",
                payload / "bc250-control-service",
            )
            for source, name in (
                (
                    ROOT / "desktop-control" / "service" / "bc250_control_service",
                    "bc250_control_service",
                ),
                (ROOT / "backend" / "bc250_control", "bc250_control"),
                (ROOT / "backend" / "vendor" / "tomli", "tomli"),
                (ROOT / "desktop-control" / "vendor" / "dbus_next", "dbus_next"),
            ):
                shutil.copytree(source, modules / name)
            subprocess.run(
                [
                    sys.executable,
                    "-I",
                    "-c",
                    "import runpy; runpy.run_path("
                    + repr(str(payload / "bc250-control-service"))
                    + ", run_name='bc250_install_check')",
                ],
                check=True,
            )

    def test_desktop_component_is_kept_and_root_backed(self):
        persistence = (ROOT / "bc250-update-persistence.sh").read_text(
            encoding="utf-8"
        )
        storage = STORAGE.read_text(encoding="utf-8")
        for expected in (
            "COMPONENTS=(compute power ram swap cec ac3 aic desktop amdgpu)",
            "/etc/systemd/system/bc250-control.service",
            "/etc/systemd/system/bc250-desktop-control-repair.service",
            "/etc/dbus-1/system.d/io.github.keyboardspecialist.BC250Control1.conf",
        ):
            self.assertIn(expected, persistence)
        self.assertNotIn("/usr/share/polkit-1/actions/", persistence)
        repair = DESKTOP_REPAIR.read_text(encoding="utf-8")
        self.assertIn(
            "/usr/share/polkit-1/actions/"
            "io.github.keyboardspecialist.bc250-control.policy",
            repair,
        )
        self.assertIn("bc250-control.service", storage)
        self.assertIn("bc250-desktop-control-repair.service", storage)

    def test_storage_without_terminal_prints_help(self):
        result = subprocess.run(
            ["bash", str(STORAGE)],
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 1)
        self.assertIn("Usage:", result.stderr)

    def test_storage_enablement_is_safe_with_nounset(self):
        with tempfile.TemporaryDirectory() as directory:
            link = Path(directory) / "test.service"
            subprocess.run(
                [
                    "bash",
                    "-c",
                    'storage=$1; link=$2; set -- help; source "$storage" >/dev/null; '
                    'install() { :; }; install_enablement "$link" test.service',
                    "_",
                    str(STORAGE),
                    str(link),
                ],
                check=True,
                capture_output=True,
                text=True,
            )
            self.assertEqual(Path(os.readlink(str(link))), Path("../test.service"))

    def test_shared_service_payload_is_user_traversable(self):
        source = SHARED_INSTALL.read_text(encoding="utf-8")
        self.assertIn(
            'SHARED_STAGE=$(mktemp -d /var/lib/bc250-control/.desktop-stage.XXXXXX)\n'
            '    chmod 0755 "$SHARED_STAGE"',
            source,
        )
        repair = DESKTOP_REPAIR.read_text(encoding="utf-8")
        self.assertIn('chmod 0755 "$PAYLOAD_DIR"', repair)

    def test_all_shell_entrypoints_parse(self):
        scripts = [
            "bc250-toolkit.sh",
            "bc250-storage.sh",
            "bc250-update-persistence.sh",
            "bc250-power.sh",
            "bc250-ram-split.sh",
            "bc250-swap.sh",
            "bc250-40cu.sh",
            "bc250-cec.sh",
            "aic8800/steamdeck-setup.sh",
            "aic8800/aic8800-ensure-modules.sh",
            "fetch-steamos-package.sh",
            "bc250-audio-fix/fetch-sources.sh",
            "bc250-audio-fix/build.sh",
            "bc250-audio-fix/prepare-kernel.sh",
            "bc250-audio-fix/patch-driver.sh",
            "bc250-audio-fix/boot-config.sh",
            "decky-plugin/install.sh",
            "desktop-control/install.sh",
            "desktop-control/shared-service-install.sh",
            "trainer/install.sh",
            "desktop-control/bc250-desktop-control-repair",
        ]
        subprocess.run(
            ["bash", "-n", *(str(ROOT / script) for script in scripts)],
            check=True,
        )


if __name__ == "__main__":
    unittest.main()
