#!/usr/bin/env bash
# Manage the scheduler policy required by the GFX1013 async-compute repair.
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
SCHED_CONFIG=${SCHED_CONFIG:-/etc/default/grub.d/bc250-amdgpu.cfg}
GRUB_DEFAULT=${GRUB_DEFAULT:-/etc/default/grub}
GRUB_CFG=${GRUB_CFG:-/efi/EFI/steamos/grub.cfg}
PROC_CMDLINE=${PROC_CMDLINE:-/proc/cmdline}
KEEP_FILE=${AMDGPU_KEEP_FILE:-/etc/atomic-update.conf.d/bc250-amdgpu.conf}
PERSISTENCE_SH=${PERSISTENCE_SH:-$HERE/../bc250-update-persistence.sh}
GRUB_CONFIG_LOCK=${GRUB_CONFIG_LOCK:-/run/lock/bc250-grub-config.lock}
RECOVERY_UNIT='/etc/systemd/system/bc250-persistence-recovery.service'
RECOVERY_WANTS='/etc/systemd/system/local-fs.target.wants/bc250-persistence-recovery.service'
STORAGE_UNIT='/etc/systemd/system/var-lib-bc250\x2dcontrol.mount'
STORAGE_WANTS='/etc/systemd/system/local-fs.target.wants/var-lib-bc250\x2dcontrol.mount'

ROOTFS_WAS_READONLY=0
TRANSACTION_STARTED=0
TRANSACTION_OK=0
WORK=
HAD_CONFIG=0
HAD_GRUB=0
HAD_KEEP=0

log() { echo "[bc250-amdgpu] $*"; }
die() { log "$*" >&2; exit 1; }
require_root() { [[ $EUID -eq 0 ]] || die "Run with sudo."; }

render_config() {
    cat <<'EOF'
# BC-250 AMDGPU scheduler policy managed by bc250-audio-fix/boot-config.sh.
# Required by the GFX1013 async-compute queue repair.
GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT:-} amdgpu.sched_policy=2"
EOF
}

config_owned() {
    [[ -f "$SCHED_CONFIG" && ! -L "$SCHED_CONFIG" ]] || return 1
    cmp -s "$SCHED_CONFIG" <(render_config)
}

keep_file_owned() {
    [[ -f "$KEEP_FILE" && ! -L "$KEEP_FILE" ]] || return 1
    cmp -s "$KEEP_FILE" <(render_keep_file)
}

render_keep_file() {
    printf '%s\n' \
        '# Toolkit state preserved by SteamOS atomic updates.' \
        '# Generated by bc250-update-persistence.sh.' \
        "$SCHED_CONFIG" "$RECOVERY_UNIT" "$RECOVERY_WANTS" \
        "$STORAGE_UNIT" "$STORAGE_WANTS"
}

secure_root_file() {
    local owner mode
    owner=$(stat -c %u "$1") || return 1
    mode=$(stat -c %a "$1") || return 1
    [[ "$owner" == 0 && "$mode" =~ ^[0-7]+$ ]] || return 1
    (( (8#$mode & 8#022) == 0 ))
}

foreign_policy_source() {
    local candidate
    for candidate in "$GRUB_DEFAULT" "${SCHED_CONFIG%/*}"/*; do
        [[ "$candidate" != "$SCHED_CONFIG" && -f "$candidate" && ! -L "$candidate" ]] \
            || continue
        if grep -Eq "(^|[[:space:]\"'])amdgpu\\.sched_policy=" "$candidate"; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    return 1
}

preflight() {
    local source
    if [[ -e "$SCHED_CONFIG" || -L "$SCHED_CONFIG" ]]; then
        config_owned || die "Existing scheduler configuration is not toolkit-owned: $SCHED_CONFIG"
        secure_root_file "$SCHED_CONFIG" \
            || die "Scheduler configuration must be root-owned and not group/other-writable: $SCHED_CONFIG"
    fi
    if [[ -e "$KEEP_FILE" || -L "$KEEP_FILE" ]]; then
        keep_file_owned || die "Existing AMDGPU keep list is not toolkit-owned: $KEEP_FILE"
        secure_root_file "$KEEP_FILE" \
            || die "AMDGPU keep list must be root-owned and not group/other-writable: $KEEP_FILE"
    fi
    if source=$(foreign_policy_source); then
        die "Another GRUB source already sets amdgpu.sched_policy: $source"
    fi
    command -v grub-mkconfig >/dev/null 2>&1 \
        || command -v update-grub >/dev/null 2>&1 \
        || die "Neither update-grub nor grub-mkconfig is available."
    if [[ -e "$GRUB_CFG" || -L "$GRUB_CFG" ]]; then
        [[ -f "$GRUB_CFG" && ! -L "$GRUB_CFG" ]] \
            || die "Refusing unsafe generated GRUB path: $GRUB_CFG"
    fi
    [[ -f "$PERSISTENCE_SH" && ! -L "$PERSISTENCE_SH" ]] \
        || die "Update persistence helper missing or unsafe: $PERSISTENCE_SH"
}

validate_generated_grub() {
    local path="$1" expected="$2"
    [[ -f "$path" && ! -L "$path" ]] || return 1
    awk -v expected="$expected" '
        $1 ~ /^linux/ || ($1 == "steamenv_boot" && $2 ~ /^linux/) {
            lines++
            on_line = 0
            for (i = 1; i <= NF; i++) {
                if ($i ~ /^amdgpu\.sched_policy=/) {
                    on_line++
                    if (expected == "" || $i != "amdgpu.sched_policy=" expected)
                        bad = 1
                }
            }
            if ((expected == "" && on_line != 0) || (expected != "" && on_line != 1))
                bad = 1
        }
        END {
            exit(lines > 0 && !bad ? 0 : 1)
        }
    ' "$path"
}

regenerate_grub() {
    local expected="$1" tmp
    mkdir -p "${GRUB_CFG%/*}"
    if command -v grub-mkconfig >/dev/null 2>&1; then
        tmp=$(mktemp "${GRUB_CFG%/*}/.bc250-grub.XXXXXX") || return 1
        if ! grub-mkconfig -o "$tmp" \
            || ! validate_generated_grub "$tmp" "$expected"; then
            rm -f "$tmp"
            return 1
        fi
        chmod 0644 "$tmp"
        mv -f "$tmp" "$GRUB_CFG"
    else
        update-grub || return 1
        validate_generated_grub "$GRUB_CFG" "$expected"
    fi
}

restore_file() {
    local source="$1" target="$2" tmp
    mkdir -p "${target%/*}"
    tmp=$(mktemp "${target%/*}/.bc250-restore.XXXXXX") || return 1
    cp -p "$source" "$tmp" || { rm -f "$tmp"; return 1; }
    mv -f "$tmp" "$target"
}

restore_transaction() {
    if [[ $HAD_CONFIG -eq 1 ]]; then restore_file "$WORK/config" "$SCHED_CONFIG" || true
    else rm -f "$SCHED_CONFIG"
    fi
    if [[ $HAD_GRUB -eq 1 ]]; then restore_file "$WORK/grub" "$GRUB_CFG" || true
    else rm -f "$GRUB_CFG"
    fi
    if [[ $HAD_KEEP -eq 1 ]]; then restore_file "$WORK/keep" "$KEEP_FILE" || true
    else rm -f "$KEEP_FILE"
    fi
}

cleanup() {
    local rc=$?
    trap - EXIT
    if [[ $TRANSACTION_STARTED -eq 1 && $TRANSACTION_OK -eq 0 ]]; then
        log "Boot-policy update failed; restoring previous configuration." >&2
        restore_transaction
    fi
    [[ -z "$WORK" ]] || rm -rf "$WORK"
    if [[ $ROOTFS_WAS_READONLY -eq 1 ]]; then
        steamos-readonly enable || rc=1
    fi
    exit "$rc"
}
trap cleanup EXIT

begin_transaction() {
    WORK=$(mktemp -d /tmp/bc250-amdgpu-boot.XXXXXX)
    if [[ -f "$SCHED_CONFIG" ]]; then cp -p "$SCHED_CONFIG" "$WORK/config"; HAD_CONFIG=1; fi
    if [[ -f "$GRUB_CFG" ]]; then cp -p "$GRUB_CFG" "$WORK/grub"; HAD_GRUB=1; fi
    if [[ -f "$KEEP_FILE" ]]; then cp -p "$KEEP_FILE" "$WORK/keep"; HAD_KEEP=1; fi
    if steamos-readonly status 2>/dev/null | grep -qi enabled; then
        steamos-readonly disable
        ROOTFS_WAS_READONLY=1
    fi
    TRANSACTION_STARTED=1
}

lock_grub_config() {
    [[ ${BC250_GRUB_LOCK_HELD:-0} != 1 ]] || return 0
    command -v flock >/dev/null 2>&1 \
        || die "flock is required for safe GRUB changes."
    exec 8> "$GRUB_CONFIG_LOCK" || die "Could not open $GRUB_CONFIG_LOCK"
    flock 8 || die "Could not lock $GRUB_CONFIG_LOCK"
}

cmd_install() {
    require_root
    lock_grub_config
    preflight
    begin_transaction
    mkdir -p "${SCHED_CONFIG%/*}"
    render_config > "$SCHED_CONFIG.new.$$"
    chown root:root "$SCHED_CONFIG.new.$$"
    chmod 0644 "$SCHED_CONFIG.new.$$"
    mv -f "$SCHED_CONFIG.new.$$" "$SCHED_CONFIG"
    regenerate_grub 2 || die "GRUB regeneration did not produce amdgpu.sched_policy=2."
    bash "$PERSISTENCE_SH" install amdgpu
    keep_file_owned || die "Atomic-update retention was not installed for $SCHED_CONFIG."
    TRANSACTION_OK=1
    log "Configured persistent amdgpu.sched_policy=2. Reboot to activate it."
}

cmd_remove() {
    require_root
    if [[ ! -e "$SCHED_CONFIG" && ! -L "$SCHED_CONFIG" \
        && ! -e "$KEEP_FILE" && ! -L "$KEEP_FILE" \
        && ${BC250_FORCE_GRUB_REGEN:-0} != 1 ]]; then
        log "No toolkit-managed scheduler policy is installed."
        return 0
    fi
    lock_grub_config
    preflight
    begin_transaction
    rm -f "$SCHED_CONFIG"
    if [[ ${BC250_SKIP_GRUB_REGEN:-0} != 1 ]]; then
        regenerate_grub "" || die "GRUB regeneration did not remove amdgpu.sched_policy."
    fi
    bash "$PERSISTENCE_SH" remove amdgpu
    TRANSACTION_OK=1
    log "Removed the toolkit-managed AMDGPU scheduler policy."
}

active_policy() {
    local token
    [[ -r "$PROC_CMDLINE" ]] || return 1
    for token in $(< "$PROC_CMDLINE"); do
        [[ "$token" == amdgpu.sched_policy=2 ]] || continue
        return 0
    done
    return 1
}

configured() {
    config_owned && keep_file_owned \
        && secure_root_file "$SCHED_CONFIG" && secure_root_file "$KEEP_FILE" \
        && validate_generated_grub "$GRUB_CFG" 2
}

cmd_status() {
    if configured; then
        if active_policy; then
            log "scheduler policy: configured and active (amdgpu.sched_policy=2)"
        else
            log "scheduler policy: configured; reboot needed (amdgpu.sched_policy=2)"
        fi
        return 0
    fi
    if [[ -e "$SCHED_CONFIG" || -L "$SCHED_CONFIG" \
        || -e "$KEEP_FILE" || -L "$KEEP_FILE" ]]; then
        log "scheduler policy: incomplete or unrecognized"
    else
        log "scheduler policy: not configured"
        log "install with: sudo bash $0 install"
    fi
    return 1
}

case "${1:-}" in
    install) [[ $# -eq 1 ]] || die "Usage: $0 install"; cmd_install ;;
    remove) [[ $# -eq 1 ]] || die "Usage: $0 remove"; cmd_remove ;;
    status) [[ $# -eq 1 ]] || die "Usage: $0 status"; cmd_status ;;
    configured) [[ $# -eq 1 ]] || exit 2; configured ;;
    present)
        [[ $# -eq 1 ]] || exit 2
        [[ -e "$SCHED_CONFIG" || -L "$SCHED_CONFIG" || -e "$KEEP_FILE" || -L "$KEEP_FILE" ]]
        ;;
    policy-present)
        [[ $# -eq 1 ]] || exit 2
        [[ -e "$SCHED_CONFIG" || -L "$SCHED_CONFIG" ]]
        ;;
    *) die "Usage: $0 {install|remove|status|configured|present|policy-present}" ;;
esac
