#!/usr/bin/env python3
import os
import sys


SERVICE_DIR = os.path.dirname(os.path.realpath(__file__))
PY_MODULES = os.path.join(SERVICE_DIR, "py_modules")
if PY_MODULES not in sys.path:
    sys.path.insert(0, PY_MODULES)

from bc250_control_service.main import main


if __name__ == "__main__":
    main()
